version: "2.2"

services:
  cube:
    image: cube
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_BQ_PROJECT_ID=analytics-147612
      - CUBEJS_DB_BQ_CREDENTIALS=ewogICJhY2NvdW50IjogIiIsCiAgImNsaWVudF9pZCI6ICI3NjQwODYwNTE4NTAtNnFyNHA2Z3BpNmhuNTA2cHQ4ZWp1cTgzZGkzNDFodXIuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLAogICJjbGllbnRfc2VjcmV0IjogImQtRkw5NVExOXE3TVFtRnBkN2hIRDBUeSIsCiAgInJlZnJlc2hfdG9rZW4iOiAiMS8vMDZBMXRQR20xT29vbkNnWUlBUkFBR0FZU053Ri1MOUlyR0hRcUZUXzhvNFB5cFFUakRpd3MxdU0wWVhCc21IVDhGN01Gd200V2pBMVVNOTA0Tmo3enp6TUs2VzJXUHBzT0J6SSIsCiAgInR5cGUiOiAiYXV0aG9yaXplZF91c2VyIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9
      - CUBEJS_DB_TYPE=bigquery
      - CUBEJS_API_SECRET=35e62317c3f6223e71ea5857cf27bd72
      - CUBEJS_EXTERNAL_DEFAULT=true
      - CUBEJS_SCHEDULED_REFRESH_DEFAULT=false
      - CUBEJS_SCHEMA_PATH=model
      - CUBEJS_DB_BQ_LOCATION=EU
      - CUBEJS_PRE_AGGREGATIONS_SCHEMA=dev_gsokolov_preagg
      - CUBEJS_SQL_USER=cube
      - CUBEJS_SQL_PASSWORD=46022dc9800ec0e54440eddc7d35aa59
      - CUBEJS_CUBESTORE_HOST=localhost
      - CUBEJS_PRE_AGGREGATIONS_BUILDER=false
    volumes:
      - .:/cube/conf
